title: Bastian Fischer
url: https://bastian-fischer.dev

main_title:
  name: Fischer
  subname: elyps.
  surname: Bastian

author:
  name: Bastian elyps. Fischer
  email: kontakt[at]bastian-fischer[dot]dev
  status: Swift Enthusiast
  desc: >
    Bastian Fischer is a Software-Developer, UI/UX-Designer and Open-Sourcerer 😉 from Germany, SH, Kiel.
  github:
    profileURL: https://github.com/elyps

description: > # this means to ignore newlines until "show_excerpts:"
  Software Developer, UI/UX Designer & Open-Sourcerer

show_excerpts: true # set to true to show excerpts on the homepage

baseurl_root: .
lang: de

feed:
  posts_limit: 20
  disable_in_development: false
  collections:
    - projects
    - posts
  tags: true
  categories:
    - development

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

collections:
  projects:
    output: true
  posts:
    output: true
    sidebar_label: Articles

  # generate social links in footer
  social_links:
    twitter: elypsCC
    github:  elyps
    devto: elyps
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: bastian-fischer
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    googleplus: bastian-fischer
    # microdotblog: jekyll
    # keybase: jekyll
    # google_scholar_id: qc6CJjYAAAAJ

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: minima

# i18n
# language_data: data.lang.%%
# language_includes_dir: _i18n
languages: ['de', 'en']
exclude_from_localizations: ["js", "images", "css", "sass"]

jekyll_admin:
  hidden_links:
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"

plugins:
 - jekyll-environment-variables
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-multiple-languages-plugin
